Add devise11
faisalakb/Rails-Blog-App pull request #9
Opened 2023-11-30 19:46 UTC by faisalakb

In this project apply the following features :100: 

Remove current_user method in ApplicationController, devise will provide us with one.
[Install and setup devise](https://github.com/heartcombo/devise#getting-started).

    Can register a new user.
    User logs in with a combination of email and password.
    Hashed password should be stored in the database.
    Ask for confirmation of email.
    Can reset password.

2023-11-30 20:55 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi Team
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![0bd223a2b156e0eaf61a713e84c3d3b7](https://user-images.githubusercontent.com/57408419/255594021-109e7375-12de-4f5b-9e29-79eefc52e35a.gif)



## To highlight :champagne: 


- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 20:55 UTC, joel-kalema commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ] Good job adding models, however, make sure you enable the `:confirmable` You should see something similar to what is below:

```ruby
devise :database_authenticatable, :registerable,
	   :recoverable, :rememberable, :validatable, :confirmable
```

2023-11-30 20:55 UTC, joel-kalema commented on app/views/devise/registrations/new.html.erb
> +
- [ ] Good job adding devise, however, When I'm trying to sign up I'm getting an error
![Capture1](https://github.com/faisalakb/Rails-Blog-App/assets/57408419/45a87c96-12f7-4870-8ee3-2f15eae41fde)

Kindly, fix it 😄 .

- [ ] Also, please modify your styling as it is [required](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=Modify%20the%20views%20in%20devise%20for%20registration%20and%20login%20to%20match%20the%20wireframes%20from%20the%20Sneak%20Peek%20and%20your%20styling.)
![Capture](https://github.com/faisalakb/Rails-Blog-App/assets/57408419/5aeba0d3-931f-4464-9bd9-8a9f6496569f)

2023-12-01 13:27 UTC, faisalakb commented
Please check, i updated the above comments

2023-12-01 13:57 UTC, FrederickMih approved these changes
## Hi :raising_hand: :raising_hand: @, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/LtkRsMZNSChvICUFhV/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- Email confirmation is enabled during the registration process as requested :+1: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-01 13:57 UTC, FrederickMih commented on app/views/devise/registrations/new.html.erb
> +  </div>
- [Optional] Hi @faisalakb, I think its important to make the registration process as quick and easy as possible to avoid the risk of losing users. Let's kindly make it simple with the name and email input fields :+1:

2023-12-01 14:01 UTC, faisalakb commented
Thanks for the time and review.

2023-12-01 14:01 UTC, merged